### ISSUE TITLE
This example appears to have lost a few lines

### ISSUE THREAD

**Issue by jons-aura** [ExamRef70-483/Sample-Code#1]
https://github.com/ExamRef70-483/Sample-Code/blob/6873b0161a96dd78d8202dac43906ff43ed6465d/LISTING%201-13%E2%80%82Task%20Factory/LISTING%201-13%E2%80%82Task%20Factory/Program.cs#L16-L20

**Comment by CrazyRobMiles** [comment]
Hi. This example was dropped because TaskFactory has been replaced by Task.Factory.StartNew which you can see used in Listing 1-17. It should never have made it to GitHub. However, I've finished off the example code and added some comments so that it makes sense. Thanks for raising the issue.
